### ISSUE TITLE
typescript error when importing in react project

### ISSUE THREAD

**Issue by sepehr-safari** [nostr-dev-kit/ndk#114]
hey, importing `ndk` in a `Vite, React, Typescript` project complains with this error:
![image](https://github.com/nostr-dev-kit/ndk/assets/25853688/0ffd6c84-2902-49a1-bcd1-62dc3fabea10)

PS: this error is not showing when using a `local build of ndk`, it might be something related to the build process!

**Comment by pablof7z** [comment]
hmmm, do you have a reproducable repo to try to debug?

we might need the help of someone like @wladiston who understands these things much better than I do to understand why this might happen 😅

**Comment by sepehr-safari** [comment]
sure! just made this repo for you:
https://github.com/sepehr-safari/tst

the funnies part is that it's working fine when I use a local build of your ndk without any changes! the problem happens when using it with the hosted package from npm registery.

**Comment by pablof7z** [comment]
can you try with version 2.0.2?

**Comment by sepehr-safari** [comment]
BOOM! now working. good job!

**Comment by wladiston** [comment]
I'm super dummy when it comes to NIP and other stuff though. We should a channel to share some knowledge around the NDK
