### ISSUE TITLE
[DOCS] Add a CONTRIBUTING file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [nostr-dev-kit/ndk#122]
Feature request

#### Problem or desire

The repository looks incomplete because of the missing CONTRIBUTING.md file to guide the first-time contributors while contributing to the repository, I want to add that file to the repo.

#### Proposal

Add the CONTRIBUTING file to the repository with guidelines.

Kindly assign me this issue.

**Comment by gazhayes** [comment]
Hi Shubham, as engineers we identify and solve problems. 

Is the lack of a `CONTRIBUTING.MD` file preventing you from doing this?

**Comment by pablof7z** [comment]
note1n0s5mfcfuxwj88yeqwkfwz3y6xgwldd90v6rme3mvvckj0t5kshsvx8uf5
