### ISSUE TITLE
profileFromEvent throws when a profile is broken; should it?

### ISSUE THREAD

**Issue by gzuuus** [nostr-dev-kit/ndk#138]
I am recently noticing that I get the following error when using a filter containing the 'search' parameter like the following: '{ kinds: [0], search: searchQuery}'. I noticed this using the latest version: "@nostr-dev-kit/ndk": "^2.0.5". 
Debugging a bit I see that if I only use relays with nip50 in my 'explicitRelayUrls' it works fine, however if I add relays that are not compatible I get the error, in previous versions this did not happen and the search was done even if not all the relays in my 'explicitRelayUrls' were compatible with nip50.
```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    profileFromEvent index.mjs:1955
    setEvent index.mjs:86
    eventReceived index.mjs:1861
    eventReceived index.mjs:456
    eventReceived index.mjs:402
    executeSubscriptionsConnected index.mjs:628
    handleNext index.js:462
    handleNext index.js:462
    setInterval handler*relayInit/connectRelay/connectionPromise</ws.onmessage index.js:435
    connectionPromise index.js:432
    connectRelay index.js:411
    connect index.js:518
    connect index.mjs:53
    connect index.mjs:692
    connect index.mjs:3882
    connect index.mjs:4118
    instance +layout.svelte:58
    run utils.js:41
    mount_component Component.js:47
    flush scheduler.js:99
    init Component.js:164
    Root root.svelte:1024
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Root> proxy.js:349
    initialize client.js:288
    _hydrate client.js:1836
    start start.js:22
    <anonymous> (index):9067
    promise callback* (index):9066

```

**Comment by pablof7z** [comment]
do you have an isolated example code of this? that backtrace seems quite unrelated to a search filter! 🤔

**Comment by pablof7z** [comment]
ah, I think what's happening here is that you are getting back a kind:0 with a broken JSON and it's exploding [here](https://github.com/nostr-dev-kit/ndk/blob/master/ndk/src/user/profile.ts#L23) not sure if it's a good idea to catch this or better let the application handle it

**Comment by erskingardner** [comment]
Looks like we're now catching failures for this `JSON.parse` call. Going to close. Re-open if needed.
