### ISSUE TITLE
Outbox: ["NOTICE","ERROR: bad req: subscription id too long"]

### ISSUE THREAD

**Issue by reyamir** [nostr-dev-kit/ndk#145]
Hi,
I've a small issue when using outbox for contact list

If I enable outbox here:
```
const user = instance.getUser({ pubkey });
await user.follows(undefined, outbox) <- outbox: true
```

NDK will generate very long subscription id, so I will get error from relay 
<img width="722" alt="image" src="https://github.com/nostr-dev-kit/ndk/assets/123083837/5d5ebaaf-f72d-45bd-a8e2-e27811645c23">

<img width="722" alt="image" src="https://github.com/nostr-dev-kit/ndk/assets/123083837/b218442e-b6f6-4ff8-972c-a53d829be43e">

**Comment by reyamir** [comment]
I wonder remove subId from `relayList()` can help? https://github.com/nostr-dev-kit/ndk/blob/cd7a5060bf7f4f17a7c0ca6ecfb2bf26f4a35e05/ndk/src/user/index.ts#L242C18-L242C18

**Comment by pablof7z** [comment]
I'll fix this today

**Comment by pablof7z** [comment]
fixed and new version released
