### ISSUE TITLE
.sign and .publish do not generate event ids

### ISSUE THREAD

**Issue by jacany** [nostr-dev-kit/ndk#15]
When signing an event with `NDKEvent.sign` or publishing an event (and doing effectively the same thing) with `NDKEvent.publish` or `NDK.publish` the pubkey is inserted, but the event id is left empty. The id value is there but has no content, and thus it cannot be signed.

**Comment by erskingardner** [comment]
@jacany are you still seeing this happening?

**Comment by pablof7z** [comment]
Closing. @jacany reopen if this still gives you trouble 🙏
