### ISSUE TITLE
`verifySignature` is a possible performance bottleneck when using NDK in Node.js

### ISSUE THREAD

**Issue by steliosrammos** [nostr-dev-kit/ndk#151]
For context, `NDK` has a dependency on `nostr-tools` which it uses to handle relay WS connections. `nostr-tools` implements a `verifySignature` function to verify an Event's signature, and that function is called for every event coming through a relay subscription. 

That seems to be the root cause of a performance bottleneck in `NDK`. `verifySignature` is a synchronous operation, and can take up significant CPU time. Here's a screenshot of a profile produced by calling `NDK.fetchEvents` (amongst some other calls).

![photo_2023-12-05 12 07 02](https://github.com/nostr-dev-kit/ndk/assets/24457157/92820f6d-03e1-4691-91e3-06af81755603)

There are 9 calls to `verifySignature`, each taking anywhere between 100ms and 500ms. The `verifySignature` traces back to a `handleNext()` function within the `nostr-tools` lib which is implemented here: https://github.com/nbd-wtf/nostr-tools/blob/40c5337ef0b8eb47e126d721408e7798735dd06e/relay.ts#L118 and called any time a new `EVENT` message comes through the WS subscription.

I'm not sure what the best solution is here. Some ideas: 

1. Removing the dependency on `nostr-tools`. That's probably the best way forward, but it would be a big change and I imagine is not priority right now
2. Replacing `nostr-tools`'s schnorr signature verification with an async operation 
3. Surfacing the `skipVerification` sub option from `nostr-tools` and leave it up to the app using NDK to verify the signature of events or not. This is a simpler solution albeit not addressing the root cause.

Other suggestions are welcome.

**Comment by erskingardner** [comment]
Thanks for the deep drive @steliosrammos - super helpful. A few thoughts. 

- I've not looked in a while at how deeply intertwined NDK is with nostr-tools at the moment, I also would love to decouple them, but I imagine there is a lot of low level stuff that we don't necessarily want to rewrite. @pablof7z thoughts on this? you've been making a lot of changes to subs with the outbox stuff recently.
- 2 feels like it should probably be brought up on the nostr-tools repo
- 3 feels relatively quick and easy. I do think that clients should have the ability to decide if they want to turn off the client-side verification of events (thus trusting relays) but it should stay on by default IMO. 

I believe that using caching in NDK helps here, as the cached events are pulled out of the db without having to be verified a second time. Depends on the use case but that also might help in your particular case.

**Comment by fiatjaf** [comment]
There are no gains from using async operations, it will be just an added cost. JavaScript is single threaded and signature verification is a pure CPU operation, doesn't involve any IO waiting step, so there will be zero gains.

**Comment by steliosrammos** [comment]
> 2. There are no gains from using async operations, it will be just an added cost. JavaScript is single threaded and signature verification is a pure CPU operation, doesn't involve any IO waiting step.

That's true, we use a worker process when calling `verifySignature` directly, but not sure if that can be done for `nostr-tools` which is also used in the browser.

**Comment by steliosrammos** [comment]
> I believe that using caching in NDK helps here, as the cached events are pulled out of the db without having to be verified a second time. Depends on the use case but that also might help in your particular case.

Thanks for the suggestion! I played a bit with the NDK Redis Cache and I think it needs some love before we can use it in production. But if nothing else, that'd be a good thing to work on.

**Comment by pablof7z** [comment]
Just released a new version adding: `skipVerification: true` as a subscription option and `relay.trusted = true` to skip all verifications from one particular relay.

**Comment by pablof7z** [comment]
Also, the new redis-cache caches queries/results so it's a bit more useful for generic queries.
