### ISSUE TITLE
 how do i get a user's followers?

### ISSUE THREAD

**Issue by ralyodio** [nostr-dev-kit/ndk#152]
I'm having trouble figuring this out.

I want to follow a user's followers given an npub.

**Comment by pablof7z** [comment]
If you want a user's follows you just:

```typescript
const user = ndk.getUser({ npub: "npub1l2vyh47mk2p0qlsku7hg0vn29faehy9hy34ygaclpn66ukqp3afqutajft" });
const follows = await user.follows();
```

**Comment by ralyodio** [comment]
one more thing while I have you here, how would I follow a user (or list of users)?

**Comment by ralyodio** [comment]
can you respond to this?
