### ISSUE TITLE
Terminating Usage of an NDK Object

### ISSUE THREAD

**Issue by richard16611** [nostr-dev-kit/ndk#153]
What is the best practice for terminating the usage of an `NDK` object?

I have instantiated an `NDK` object and invoked the `.connect()` method. After fetching some events using `fetchEvent`, I now wish to cease using this object. Is it necessary to explicitly disconnect it? If so, is there a specific function provided for this purpose? 
Additionally, I would like to understand the role of the `.connect()` method, especially since websockets are instantiated only after the `.subscribe()` method.

**Comment by pablof7z** [comment]
Most applications typically connect to the relays and stay connected, so normally you would instantiate ndk, `ndk.connect()` it and then use `subscribe` and close them as you need.

`subscribe` issues a `connect` to relays that were explicitly passed/gathered from the outbox model if no connection exists to the relay but it's not the most common path.

Does that make sense? It sounds like maybe you have a different flow in mind where you want to receive events and then disconnect from relays? Would be curious to hear what you have in mind.

**Comment by richard16611** [comment]
I am using a function that creates a new `NDK` instance each time it's called, as shown below:

```
async function fetchEvents<K extends number>(
  filter: NDKFilter<K>,
  relays: string[],
) {
  const ndk = new NDK({ explicitRelayUrls: relays });
  await ndk.connect();

  const event = await ndk.fetchEvent(filter);
  return event
}
```

I'm aware that the recommended way is to use a single `NDK` instance throughout the app, but this approach suits my specific requirements better.
My concern is whether this pattern might lead to issues such as memory leaks or lingering open connections due to the frequent creation of new `NDK` instances. Is there a need to explicitly disconnect or delete each `NDK` instance after use to mitigate such issues? Are there any other potential problems or performance impacts I should be aware of with this implementation?

**Comment by mrkvon** [comment]
I've faced similar issue, and started doing something like:

```ts
for (const relay of ndk.pool.relays.values()) {
  relay.disconnect()
}
ndk.pool.relays.clear()
```

I don't know whether that's sufficient to prevent a memory leak.
