### ISSUE TITLE
Does the fetchEvent function support grouping queries?

### ISSUE THREAD

**Issue by richard16611** [nostr-dev-kit/ndk#154]
The docs give this example for groupable queries:

```
// Component 1
ndk.subscribe({ kinds: [0], authors: ["pubkey-1"] });

// Component 2
ndk.subscribe({ kinds: [0], authors: ["pubkey-2"] });
```

will the following also be grouped?
```
// Component 1
const eventA = await ndk.fetchEvent({ kinds: [0], authors: ["pubkey-1"] });

// Component 2
const eventB = await ndk.fetchEvent({ kinds: [0], authors: ["pubkey-2"] });
```

I assume not because it opens and closes the subscription, but I want to make sure I understand correctly.

**Comment by sepehr-safari** [comment]
no.
`ndk.fetchEvent` is not groupable. because it doesn't keep relay connections open. so it can't wait for other `ndk.fetchEvent` calls to batch together.
