### ISSUE TITLE
is it possible to split a payment (ie: take a commission)

### ISSUE THREAD

**Issue by ralyodio** [nostr-dev-kit/ndk#158]
I'm adding zapping to my site but I'd like to take a 5% commission on all zaps done on the site.

Is this possible without generating two zaps?

ie: 5% goes to my npub, 95% goes to other npub

**Comment by erskingardner** [comment]
No, that's not possible. You'll have to generate two zaps.

**Comment by ralyodio** [comment]
this code isn't working:

https://github.com/nostr-dev-kit/ndk/issues/147#issuecomment-1859175555
