### ISSUE TITLE
[feature request] Function to set NDKUser for NDKNip07Signer

### ISSUE THREAD

**Issue by fryheid** [nostr-dev-kit/ndk#16]
Every time I refresh a page NDK loses state and I have to approve sharing my public key again. But after sharing my pub key once, it can be stored somewhere else with persistence and upon refreshing the page:
- I check my storage for the presence of a public key
- If present: I create a new NDKUser using the pub key and set it to the NDKNip07Signer, so I don't have to prompt the user again
- If not present: I prompt the user to share his pub key

**Comment by erskingardner** [comment]
I think that this is less an NDK concern and more of a concern of your app since each app handles persistence differently. Happy to hear more thoughts on this though.

**Comment by erskingardner** [comment]
Closing as stale.
