### ISSUE TITLE
Invalid byte sequence

### ISSUE THREAD

**Issue by minimo-io** [nostr-dev-kit/ndk#217]
Any ideas on why this is? Thanks!
`Error: Invalid byte sequence
    at hexToBytes (utils.ts:59:47)
    at encodeBytes (index.js:1025:14)
    at Object.npubEncode (index.js:1015:10)
    at get npub (index.mjs:2897:27)`

![Screenshot 2024-04-27 at 15 34 32](https://github.com/nostr-dev-kit/ndk/assets/47158741/5541b2bf-828e-4d3a-8f7d-35ffbda1ac99)

**Comment by pablof7z** [comment]
That's from trying to use an invalid pubkey

**Comment by minimo-io** [comment]
> That's from trying to use an invalid pubkey

But isn't that curious given that I am iterating a set of `NDKUser`s returned by the `follows` method ? 🤔 Shouldn't all be valid pubkeys? Thanks again Pablo!

**Comment by pablof7z** [comment]
Not at all, a lot of people have broken follow lists. Perhaps the follows function should skip those

**Comment by minimo-io** [comment]
Got it! I keep learning here 🫡 Thanks.
