### ISSUE TITLE
Installing NDK from git source so that I can test latest doesn't work.  Also, new release soon?

### ISSUE THREAD

**Issue by jeremyd** [nostr-dev-kit/ndk#244]
I need some of these commits from the last month since the last version..  When I attempt to install from a git source, npm fails.  So I also tried a local checkout so I can use npm link or something, and when I run the build, same errors as follows:

```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```

So then I try with yarn, and it says:
```
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@nostr-dev-kit%2feslint-config-custom: Not found".
```

I am interested in running off master branch because I want the fixes for NIP42 auth and to help debug NDK in general, I dislike running old packages for stuff that's bleeding edge.  What am I missing here?  Or is the build just broken?

**Comment by jeremyd** [comment]
I think I'm in over my head here.  My humble project uses npm.  I see ndk uses pnpm and yarn.  I will need to come up to speed on these and then maybe i stand a chance of using git urls for NDK packages..  Yarn seems confused and keeps asking for a version, but the git repo has no version tags etc ..  I'm curious what your development environment looks like for doing this kind of stuff maybe it will help me understand what I would need to do.

**Comment by pablof7z** [comment]
added a BUILD.md file

**Comment by jeremyd** [comment]
Thank you!  Also please consider tagging the releases so that it would be easier to fork off an existing release.
