### ISSUE TITLE
Why requires env access?

### ISSUE THREAD

**Issue by SnowCait** [nostr-dev-kit/ndk#262]
Deno says `PermissionDenied: Requires env access, run again with the --allow-env flag`.
Other libraries does not requre it.
I don't think it is good to allow env access to libraries because it could be a security issue.
Permission control is the responsibility of apps, not libraries.
It would be better to accept parameters from constructor or method arguments.

**Comment by erskingardner** [comment]
Hmm, I'm not sure why NDK would need env access. there's nothing I'm aware of in the codebase that is asking for env access.

**Comment by pablof7z** [comment]
yeah, I don't think this is related to NDK, please reopen if you pinpoint something where this is happening.

**Comment by SnowCait** [comment]
Why not?
It's very easy to reproduce. Where else could the cause be other than the NDK?

Code (ndk.ts):
```
import NDK from "npm:@nostr-dev-kit/ndk";
new NDK();
```

Execution (--allow-read is required to read node_modules packages):
```
> deno run --allow-read .\ndk.ts
┏ ⚠️  Deno requests env access.
┠─ Learn more at: https://docs.deno.com/go/--allow-env
┠─ Run again with --allow-env to bypass this prompt.
┗ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all env permissions) >
```
