### ISSUE TITLE
[feature request] subscribe only to a specified relay/relays

### ISSUE THREAD

**Issue by michaelhall923** [nostr-dev-kit/ndk#27]
ex.
`const subscription = ndk.subscribe(filter, opts, ["wss://relay.stemstr.app"]);`

Use case: I am currently implementing NDK in Stemstr. I want to be able to fetch the main feed ONLY from the Stemstr relay, but grab replies, reactions, zaps, etc. from other relays as well.

**Comment by erskingardner** [comment]
@pablof7z could this be accomplished by simply creating a new/second instance of NDK that only connects to the single relay?

**Comment by pablof7z** [comment]
took longer to do than to type how to do it... 😅

**Comment by erskingardner** [comment]
LOL – nice one!
