### ISSUE TITLE
problem: nip07 signer cannot initiate though there is a window.nostr plugin

### ISSUE THREAD

**Issue by pqingshuang** [nostr-dev-kit/ndk#29]
![image](https://github.com/nostr-dev-kit/ndk/assets/26760878/c81f0384-3dd9-42ea-9d38-8402845f807c)

**Comment by pablof7z** [comment]
Is very likely that you hit it before it was initialized. This is a known issue with NIP-07 extensions.

**Comment by pqingshuang** [comment]
yeah i solve it by set some interval. lets close this
