### ISSUE TITLE
Allow using list of filter objects when subscribing

### ISSUE THREAD

**Issue by verbiricha** [nostr-dev-kit/ndk#37]
Would be nice if subs could be arrays of filter objects, from [NIP-1](https://github.com/nostr-protocol/nips/blob/master/01.md).

>A REQ message may contain multiple filters. In this case, events that match any of the filters are to be returned, i.e., multiple filters are to be interpreted as || conditions.

**Comment by pablof7z** [comment]
Agreed and done ✅
