### ISSUE TITLE
Add relays param for `fetchEvent` and `fetchEvents`

### ISSUE THREAD

**Issue by SamSamskies** [nostr-dev-kit/ndk#40]
It would be nice to be able to fetch events from certain relays using these helper functions. I have a use case where sometimes I need to fetch events only from one specific relay.

**Comment by SamSamskies** [comment]
Or would it make more sense to just make a separate NDK instance with that one relay?

**Comment by pablof7z** [comment]
> Or would it make more sense to just make a separate NDK instance with that one relay?

No, you would pass in a separate NDKRelaySet. `subscribe` allows it but fetchEvent(s) don't.

Probably this should be a new arg on these two functions as this is conceptually different than a filter option (ie you'll want to this this for publish and that wouldn't make sense to live as a filter option 😂)

**Comment by SamSamskies** [comment]
> Want to make a PR for this?

@erskingardner I can take a crack at it. At a quick glance, it looks like it's an easy update.
