### ISSUE TITLE
Getting a user profile erases any custom profile fields

### ISSUE THREAD

**Issue by michaelhall923** [nostr-dev-kit/ndk#42]
Profile metadata fields set by other clients (e.g. website, reactions, damus_donations) are erased and they only way to keep them when updating a user's profile is to manually fetch the kind 0 and merge the fields.

Proposed solution it to add a generic field to NDKUserProfile
```
export interface NDKUserProfile {
  [key: string]: string | undefined; // allows custom fields
  name?: string;
  displayName?: string;
  image?: string;
  banner?: string;
  bio?: string;
  nip05?: string;
  lud06?: string;
  lud16?: string;
  about?: string;
  zapService?: string;
}
```

**Comment by erskingardner** [comment]
Fixed by #45
