### ISSUE TITLE
Can't call `new NDK()` from Deno

### ISSUE THREAD

**Issue by alexgleason** [nostr-dev-kit/ndk#50]
Seems like a type exporting problem:

```ts
import NDK from 'npm:@nostr-dev-kit/ndk';

const ndk = new NDK({ explicitRelayUrls: ['wss://relay.mostr.pub'] });
```

```
This expression is not constructable.
  Type 'typeof import("file:///home/alex/.cache/deno/npm/registry.npmjs.org/@nostr-dev-kit/ndk/0.7.0/dist/index")' has no construct signatures.deno-ts(2351)
```

https://typescript.tv/errors/#TS2351

![image](https://github.com/nostr-dev-kit/ndk/assets/3639540/cdf74dac-b18e-4add-bb4e-67af50373d7f)

![image](https://github.com/nostr-dev-kit/ndk/assets/3639540/6938fab7-3cee-4dc7-b851-057a2a2e3fae)

**Comment by ralyodio** [comment]
you could try loading it with esm.sh site

**Comment by alexgleason** [comment]
Same problem. I'll look into fixing it.

![image](https://github.com/nostr-dev-kit/ndk/assets/3639540/dc47ddb5-14b1-4fb1-a3b1-5eb2ae53c74a)

**Comment by alexgleason** [comment]
https://arethetypeswrong.github.io/?p=%40nostr-dev-kit%2Fndk%402.3.0
