### ISSUE TITLE
Don't directly depend/import websocket-polyfill

### ISSUE THREAD

**Issue by verbiricha** [nostr-dev-kit/ndk#52]
Started to run into build issues in Vercel due to the polyfill being imported from ndk, apparently they don't allow to overwrite the global.Websocket object at build time anymore 🤷  My suggestions is to remove the direct dependency & import, and add some docs letting users know that they have to bring their own polyfill.

[nostr-tools](https://github.com/nbd-wtf/nostr-tool) takes that approach, from the readme:

>To use this on Node.js you first must install websocket-polyfill

Can send a patch if i get ACK

**Comment by jeremyd** [comment]
+1 for this, I can't use websocket polyfill either, i've been using nostr-tools without it and it seems ok?

**Comment by jeremyd** [comment]
just for reference.  I have problems with websocket-polyfill on nextjs (not even using vercel).  My error is:
```
- error node_modules/websocket-polyfill/lib/index.js (5:0) @ eval
- error TypeError: Cannot set property WebSocket of #<Object> which has only a getter
```

For now, I'm just running a patched version of NDK to remove polyfill.  @pablof7z what do you think?  is it ok to remove?  I'm unsure why it's needed in the first place (is it just for nodejs backends or something?)

**Comment by pablof7z** [comment]
yeah, we should remove; can you send a PR?

**Comment by jeremyd** [comment]
> yeah, we should remove; can you send a PR?

https://github.com/nostr-dev-kit/ndk/pull/71

**Comment by pablof7z** [comment]
✅
