### ISSUE TITLE
problem: Could not resolve "@noble/secp256k1"

### ISSUE THREAD

**Issue by gazhayes** [nostr-dev-kit/ndk#64]
I get this error when using the latest package from npm.

If I install `@noble/secp256k1` I then get other errors from the ndk package when ndk uses secp256k1.

**Comment by erskingardner** [comment]
@gazhayes can you confirm which version of NDK you're using? I used to see this error but haven't see it in a while.

**Comment by gazhayes** [comment]
Ah thanks. Looks like NPM did something silly (surprise). I just updated manually to 0.6.0 and it's resolved.
