### ISSUE TITLE
fetchProfile throws error

### ISSUE THREAD

**Issue by ralyodio** [nostr-dev-kit/ndk#67]
```
  const loginNostr = async () => {
    const nip07signer = new NDKNip07Signer();
    const ndk = new NDK({ signer: nip07signer, explicitRelays: ['wss://relay.break-19.com'] });
    const user = await nip07signer.user();

    const user2 = await ndk.getUser(user.npub);
    const profile = await user2.fetchProfile();
    console.log(profile);
    // const feedEvents = await user2.feed();

    // console.log(feedEvents, profile, user2);
    if (Boolean(user.npub)) {
      console.log('Permission granted to read their public key:', user);
    }
  };


```

Here's the error on `fetchProfile()`:

`Uncaught (in promise) TypeError: Wrong string length: 0 (). Expected (8..5000)`

**Comment by pablof7z** [comment]
Sounds like what you're passing is not a bech32 or a filter?

**Comment by ralyodio** [comment]
which part?

**Comment by pablof7z** [comment]
sorry; I misread.

The issue is:

`    const user2 = await ndk.getUser(user.npub);`

should be

`    const user2 = await ndk.getUser({ npub: user.npub });`

are you using Typescript? it should have found that issue for you 😅

**Comment by pablof7z** [comment]
Reopen if it still gives you trouble 😉
