### ISSUE TITLE
`fetchEvent` and `fetchEvents` take different arguments

### ISSUE THREAD

**Issue by erskingardner** [nostr-dev-kit/ndk#7]
Currently, `fetchEvent` takes just a filter arg but `fetchEvents` takes both filter and options args. Unless there is a good reason not to, both these methods should take identical args.

**Comment by SamSamskies** [comment]
Should this issue be closed? I'm looking at the code now and it is possible to use `fetchEvent` with both filter and options args. There's just no example of this in the README.

https://github.com/nostr-dev-kit/ndk/blob/396aac5059eaf1b3db5299c9770f2cff22db175c/src/index.ts#L131

**Comment by erskingardner** [comment]
Yup – good to close now. :)
