### ISSUE TITLE
Error not handled on relay disconnected

### ISSUE THREAD

**Issue by Dolu89** [nostr-dev-kit/ndk#76]
When a relay comes offline, NDK crashes without the possibility to catch 

Example repo https://github.com/Dolu89/ndk-issue-relay

Add 1 or more relay in NDK constructor. Launch the program then shutdown 1 relay, it crashes without going in catches 

```
git clone https://github.com/Dolu89/ndk-issue-relay.git
cd ndk-issue-relay
npm install
node index.js
```

**Comment by pablof7z** [comment]
Thanks for the detailed report!

Version 0.8.22, which I just released should fix this.
