### ISSUE TITLE
Docs specify debug to be a boolean, but if true, this would break this line

### ISSUE THREAD

**Issue by maxns** [nostr-dev-kit/ndk#79]
https://github.com/nostr-dev-kit/ndk/blob/556fb663b4bfb33d87674a1f741f52594c69e4a8/ndk/src/index.ts#L66

if opts provided to NDK() include debug:true, this line would create problems, since the expected value here is of debug.Debugger type

**Comment by pablof7z** [comment]
Can you point me to the docs that say this is boolean? Thanks!

**Comment by maxns** [comment]
https://github.com/nostr-dev-kit/ndk/tree/master/ndk#instantiate-an-ndk-instance

"debug - boolean true/false to turn on degbugging"

**Comment by pablof7z** [comment]
thanks!
