### ISSUE TITLE
Reconnected relays are not used anymore in subs

### ISSUE THREAD

**Issue by Dolu89** [nostr-dev-kit/ndk#83]
When a relay comes offline and online again, this relay is not used anymore in current subs

Example repo https://github.com/Dolu89/ndk-issue-relay

- Add 1 or more relay in NDK constructor. 
- Shutdown 1 relay
- Turn it on again
- Then publish an event on this relay

Result -> Event is not detected in sub.on("event")

```sh
git clone https://github.com/Dolu89/ndk-issue-relay.git
cd ndk-issue-relay
npm install
node index.js
```

**Comment by sebastianmontero** [comment]
@Dolu89 I'm having the same problem, have you had any updates on this issue?

**Comment by Dolu89** [comment]
> @Dolu89 I'm having the same problem, have you had any updates on this issue?

No. Ping @pablof7z

**Comment by pablof7z** [comment]
Oh damn! Really? I'll have a look asap

**Comment by sebastianmontero** [comment]
Hi @pablof7z any update on this issue?

**Comment by pablof7z** [comment]
Fixed in `master`, will cut a release in a few days after

**Comment by sebastianmontero** [comment]
Great! Thanks @pablof7z!
