### ISSUE TITLE
Move non-runtime dependencies to `devDependencies`

### ISSUE THREAD

**Issue by wbobeirne** [nostr-dev-kit/ndk#89]
Many of the dependencies in package.json `"dependencies"` are only needed for development and at built time. This requires people to download these packages unnecessarily.

Some unnecessary dependencies:
* `@typescript-eslint/*`
* `esbuild*`
* `eslint*`
* `esm-loader-typescript`
* `tsd`

I only checked with `@nostr-dev-kit/ndk` but it would be worth checking others.

**Comment by erskingardner** [comment]
Mostly fixed by #95 – I'll keep an eye on this going forward.
