### ISSUE TITLE
TypeError: event.react is not a function

### ISSUE THREAD

**Issue by sroertgen** [nostr-dev-kit/ndk#93]
I just saw that you implemented a convenience function for reacting to an event: https://github.com/nostr-dev-kit/ndk/blob/master/ndk/README.md#reacting-to-an-event

But I get an error that it is not a function.

I also can't find it in https://github.com/nostr-dev-kit/ndk/blob/master/ndk/src/events/index.ts

**Comment by HolgerHatGarKeineNode** [comment]
README.md seems to be outdated.

I did this in my code:

```javascript
const ndkEvent = new NDKEvent(this.$store.ndk.ndk);
ndkEvent.content = emoji;
ndkEvent.kind = eventKind.reaction;
ndkEvent.tags = [
    ['e', event.id],
    ['p', event.pubkey],
];
await ndkEvent.publish();
```

**Comment by sepehr-safari** [comment]
patched in this PR: https://github.com/nostr-dev-kit/ndk/pull/115
now you can use native `react` method on events as already mentioned in docs: `event.react('+')`

**Comment by pablof7z** [comment]
looks like this is fixed. Closing.
